version: 2

sources:
  - name: raw
    description: Fonte de dados do banco Bigquery com as informações carregadas no bigquery
    schema: raw
    tables:

      - name: person_person
        description: Tabela com informações das pessoas
        columns:
          - name: businessentityid
            description: Chave primária da tabela de pessoas
            tests:
              - unique
              - not_null

      - name: person_address
        description: Tabela com informações do endereço das pessoas
        columns:
          - name: addressid
            description: Chave primária da tabela de endereços
            tests:
              - unique
              - not_null
      - name: person_businessentity
        description: Tabela de relacionamento entre pessoa e entidade
        columns:
          - name: businessentityid
            description: Chave primária da tabela de businessentity
            tests:
              - unique
              - not_null

      - name: person_businessentityaddress
        description: Tabela de relacionamento entre pessoa entidade e endereço
        columns:
          - name: businessentityid
            description: Chave primária da tabela de businessentityaddress
            tests:
              - unique
              - not_null

      - name: person_stateprovince
        description: Tabela com informações dos estados
        columns:
          - name: stateprovinceid
            description: Chave primária da tabela de stateprovince
            tests:
              - unique
              - not_null

      - name: person_countryregion
        description: Tabela com informações dos paises
        columns:
          - name: countryregioncode
            description: Chave primária da tabela de countryregion
            tests:
              - unique
              - not_null
      - name: hr_employee
        description: Tabela com informações dos colaboradores
        columns:
          - name: businessentityid
            description: Chave primária da tabela de hr_employee
            tests:
              - unique
              - not_null
      - name: sales_customer
        description: Tabela com informações dos clientes
        columns:
          - name: customerid
            description: Chave primária da tabela de sales_customer
            tests:
              - unique
              - not_null