version: 2

sources:
  - name: raw
    description: Fonte de dados do banco Bigquery com as informações carregadas no bigquery
    schema: raw
    tables:

## Person
      - name: person_person
        description: Tabela com informações das pessoas
        columns:
          - name: businessentityid
            description: Chave primária da tabela de pessoas
            tests:
              - unique
              - not_null
      - name: person_address
        description: Tabela com informações do endereço das pessoas
        columns:
          - name: addressid
            description: Chave primária da tabela de endereços
            tests:
              - unique
              - not_null
      - name: person_businessentity
        description: Tabela de relacionamento entre pessoa e entidade
        columns:
          - name: businessentityid
            description: Chave primária da tabela de businessentity
            tests:
              - unique
              - not_null
      - name: person_businessentityaddress
        description: Tabela de relacionamento entre pessoa entidade e endereço
        columns:
          - name: addressid
            description: Chave primária da tabela de businessentityaddress
            tests:
              - unique
              - not_null
      - name: person_stateprovince
        description: Tabela com informações dos estados
        columns:
          - name: stateprovinceid
            description: Chave primária da tabela de stateprovince
            tests:
              - unique
              - not_null
      - name: person_countryregion
        description: Tabela com informações dos paises
        columns:
          - name: countryregioncode
            description: Chave primária da tabela de countryregion
            tests:
              - unique
              - not_null

## Human Resources
      - name: hr_employee
        description: Tabela com informações dos colaboradores
        columns:
          - name: businessentityid
            description: Chave primária da tabela de hr_employee
            tests:
              - unique
              - not_null

## Sales
      - name: sales_customer
        description: Tabela com informações dos clientes
        columns:
          - name: customerid
            description: Chave primária da tabela de sales_customer
            tests:
              - unique
              - not_null
      - name: sales_salesreason
        description: Tabela com informações do motivo de vendas
        columns:
          - name: salesreasonid
            description: Chave primária da tabela de salesreason
            tests:
              - unique
              - not_null
      - name: sales_salesperson
        description: Tabela com informações dos vendedores
        columns:
          - name: businessentityid
            description: Chave primária para registros SalesPerson. Chave estrangeira para Employee.BusinessEntityID
            tests:
              - unique
              - not_null
      - name: sales_salesorderheader
        description: Tabela com informações das datas das vendas
        columns:
          - name: salesorderid
            description: Chave primária para registros das vendas.
            tests:
              - unique
              - not_null
      - name: sales_salesorderdetail
        description: Tabela com informações dos detalhes das vendas
        columns:
          - name: salesorderdetailid
            description: Chave primária para registros dos detalhes das vendas.
            tests:
              - unique
              - not_null
      - name: sales_creditcard
        description: Tabela com informações dos detalhes dos cartóes
        columns:
          - name: creditcardid
            description: Chave primária dos cartões.
            tests:
              - unique
              - not_null
      - name: sales_store
        description: Tabela com informações dos detalhes das lojas
        columns:
          - name: businessentityid
            description: Chave primária das lojas.
            tests:
              - unique
              - not_null
      - name: sales_salesorderheadersalesreason
        description: Tabela de relacionamento entre a razao e as vendas
        columns:
          - name: salesreasonid
            description: Chave primária das razoes.
            tests:
              - unique
              - not_null
## Production
      - name: production_product
        description: Tabela com informações dos produtos
        columns:
          - name: productid
            description: Chave primária para registros dos produtos.
            tests:
              - unique
              - not_null
      - name: production_productmodel
        description: Tabela com informações dos produtos
        columns:
          - name: productmodelid
            description: Chave primária para registros dos modelos de produtos.
            tests:
              - unique
              - not_null
      - name: production_productsubcategory
        description: Tabela com informações dos produtos
        columns:
          - name: productsubcategoryid
            description: Chave primária para registros da subcategoria de produtos.
            tests:
              - unique
              - not_null    
      - name: production_productcategory
        description: Tabela com informações dos produtos
        columns:
          - name: productcategoryid
            description: Chave primária para registros da categoria de produtos.
            tests:
              - unique
              - not_null                                    